CC = gcc
CFLAGS = -Wall -Wextra -pedantic -std=c99
SRC = main.c animal.c verb.c adjective.c
OBJ = $(SRC:.c=.o)

story: $(OBJ)
	$(CC) $(CFLAGS) $^ -o $@

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

.PHONY: clean

clean:
	rm -f $(OBJ) story
